# Compiler and linker settings
CC = owcc
LD = owcc
CFLAGS = -zq -c -xc++
LDFLAGS = -zq
CP = copy
RM = del


# Source files
SRCS = main.cpp textmode.cpp mouse.cpp vga.cpp adlib.cpp

# Object files
OBJS = $(SRCS:.cpp=.obj)

# Executable name
TARGET = asciijoy.exe

# Default target
all: $(TARGET) .symbolic

# Build rule for object files
.cpp.obj: %.cpp
	$(CC) $(CFLAGS) -o $@ $<

# Link rule for the executable
$(TARGET): $(OBJS)
	$(LD) $(LDFLAGS) -o $@ $(OBJS)

# Clean rule
clean: .symbolic
	$(RM) *.obj
	$(RM) *.exe
